### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by AkshayWarrier** [nonpeep/newsify#4]
Style the current scrollbar of the website to match the theme

**Comment by qgarcia95** [comment]
@AkshayWarrier Hey man I have very little experience in web programming. For this project you guys are using Tailwind CSS and I am not sure on what file or where in the code exactly I need to edit to change the styles for the default scrollbars for the browsers. Can I implement this functionality using html and css and I can show you some samples for some custom scrollbar styles and if you guys like it you can implement it into your project or walk me through on how to do so?

**Comment by AkshayWarrier** [comment]
@qgarcia95 Hello, after some research I found out that tailwind does not have any utility classes for styling scrollbars so I looked into to it and found two possible solutions.
One is you can try adding the class 'scrollbar overflow-y-scroll' property to the body which can be found in index.html in the public folder. Then try adding styles as shown here https://play.tailwindcss.com/5samiwyr4v in the index.css file in the src folder. Make sure the stylesheet is imported somewhere.
If this does not seem to work then you can try installing this module from npm https://www.npmjs.com/package/tailwind-scrollbar and see if you are able to style the scrollbar using this, I have never used this myself so you'll have to test it out. 
As a last resort if none of these work, you can just create a separate file and show us some sample scrollbar styles.

**Comment by qgarcia95** [comment]
@AkshayWarrier Thank you very much I will work on it later tonight when I have a chance.
